apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/configmap.yaml
  - ../../manifests/deployment.yaml
  - ../../manifests/service.yaml
  - ../../manifests/ingress.yaml
  - ../../backend/manifests/configmap.yaml
  - ../../backend/manifests/deployment.yaml
  - ../../backend/manifests/service.yaml
  - ../../backend/manifests/ingress.yaml
  - ../../backend/manifests/postgres-service.yaml
  - ../../backend/manifests/postgres-statefulset.yaml
  - ../../broadcaster/manifests/configmap.yaml
  - ../../broadcaster/manifests/deployment.yaml
